CREATE DATABASE IF NOT EXISTS prenotazione_aule;
USE prenotazione_aule;

CREATE TABLE Utente (
  ID       INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  EMAIL    VARCHAR(120) NOT NULL UNIQUE,
  NOME     VARCHAR(60)  NOT NULL,
  COGNOME  VARCHAR(60)  NOT NULL,
  RUOLO    ENUM('studente','docente','ata','admin') NOT NULL,
  INDEX idx_email (EMAIL)
);

CREATE TABLE Aula (
  ID_AULA    INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  NUMERO_AULA SMALLINT UNSIGNED NOT NULL UNIQUE,
  DESCRIZIONE VARCHAR(120),
  CAPIENZA    SMALLINT UNSIGNED,
  CONSTRAINT chk_numero CHECK (NUMERO_AULA BETWEEN 1 AND 119)
);

CREATE TABLE Classe (
  ID_CLASSE INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ANNO      TINYINT UNSIGNED NOT NULL,
  SEZIONE   CHAR(1) NOT NULL,
  INDIRIZZO VARCHAR(80) NOT NULL,
  CONSTRAINT chk_anno CHECK (ANNO BETWEEN 1 AND 5)
);

CREATE TABLE Prenotazione (
  ID_PRENOTAZIONE INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ID_AULA         INT UNSIGNED NOT NULL,
  ID_UTENTE       INT UNSIGNED NOT NULL,
  DATA            DATE NOT NULL,
  ORA_INIZIO      TIME NOT NULL,
  ORA_FINE        TIME NOT NULL,
  NOTE            VARCHAR(255),
  FOREIGN KEY (ID_AULA)   REFERENCES Aula(ID_AULA)   ON DELETE RESTRICT,
  FOREIGN KEY (ID_UTENTE) REFERENCES Utente(ID)       ON DELETE CASCADE,
  CONSTRAINT chk_orario CHECK (ORA_FINE > ORA_INIZIO),
  INDEX idx_aula_data (ID_AULA, DATA)
);

CREATE TABLE Pren_Classe (
  ID_PRENOTAZIONE INT UNSIGNED NOT NULL,
  ID_CLASSE       INT UNSIGNED NOT NULL,
  PRIMARY KEY (ID_PRENOTAZIONE, ID_CLASSE),
  FOREIGN KEY (ID_PRENOTAZIONE) REFERENCES Prenotazione(ID_PRENOTAZIONE) ON DELETE CASCADE,
  FOREIGN KEY (ID_CLASSE)       REFERENCES Classe(ID_CLASSE)             ON DELETE CASCADE
);